#!/bin/bash
sudo mkdir -p appdata/space-engineers/bins/SpaceEngineersDedicated
sudo mkdir -p appdata/space-engineers/bins/steamcmd
sudo mkdir -p appdata/space-engineers/config/World
sudo mkdir -p appdata/space-engineers/config/Plugins
if [ ! -f ./appdata/space-engineers/config/World/Sandbox.sbc ]; then
    echo "World not found, initalizing empty star system..."
    sudo unzip -n star-system.zip -d ./appdata/space-engineers/config
fi

#container executes server as 1000:1000
if [ "$(stat -c '%u' appdata)" != "1000" ]; then
    echo "Setting owner of appdata to UID 1000"
    sudo chown -R 1000:1000 appdata
fi

# Checks which version of docker compose is available
DOCKER_CMD="docker-compose"
which ${DOCKER_CMD} >& /dev/null
if [ $? != 0 ]; then
    DOCKER_CMD="docker compose"
fi
 
sudo ${DOCKER_CMD} up -d
sudo ${DOCKER_CMD} logs -f
